
package org.fri.sms.module;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.fri.cfg.rootCfg;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(
		name = "SmsServiceImpService",
		targetNamespace = "http://imp.service/",
		wsdlLocation = "http://210.12.165.110:8088/Smsjws/service/sms?wsdl")
public class SmsServiceImpService
extends Service
{
	private final static URL SMSSERVICEIMPSERVICE_WSDL_LOCATION;
	private final static WebServiceException SMSSERVICEIMPSERVICE_EXCEPTION;
	private final static QName SMSSERVICEIMPSERVICE_QNAME = new QName("http://imp.service/", "SmsServiceImpService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(rootCfg.sms_module_url);			
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		SMSSERVICEIMPSERVICE_WSDL_LOCATION = url;
		SMSSERVICEIMPSERVICE_EXCEPTION = e;
	}

	public SmsServiceImpService() {
		super(__getWsdlLocation(), SMSSERVICEIMPSERVICE_QNAME);
	}

	public SmsServiceImpService(WebServiceFeature... features) {
		super(__getWsdlLocation(), SMSSERVICEIMPSERVICE_QNAME, features);
	}

	public SmsServiceImpService(URL wsdlLocation) {
		super(wsdlLocation, SMSSERVICEIMPSERVICE_QNAME);
	}

	public SmsServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SMSSERVICEIMPSERVICE_QNAME, features);
	}

	public SmsServiceImpService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SmsServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return
	 *     returns SmsService
	 */
	@WebEndpoint(name = "SmsServiceImpPort")
	public SmsService getSmsServiceImpPort() {
		return super.getPort(new QName("http://imp.service/", "SmsServiceImpPort"), SmsService.class);
	}

	/**
	 * 
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns SmsService
	 */
	@WebEndpoint(name = "SmsServiceImpPort")
	public SmsService getSmsServiceImpPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://imp.service/", "SmsServiceImpPort"), SmsService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (SMSSERVICEIMPSERVICE_EXCEPTION!= null) {
			throw SMSSERVICEIMPSERVICE_EXCEPTION;
		}
		return SMSSERVICEIMPSERVICE_WSDL_LOCATION;
	}

}
